# Generated by Django 2.2.12 on 2020-06-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'classification',
                'verbose_name_plural': 'classifications',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, unique=True)),
                ('classification', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='classifications.Classification')),
                ('supporters', models.ManyToManyField(blank=True, related_name='causes', to='accounts.Member')),
            ],
            options={
                'verbose_name': 'cause',
                'verbose_name_plural': 'causes',
            },
        ),
    ]
