# Generated by Django 2.2.12 on 2020-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
