# Generated by Django 2.2.12 on 2020-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200619_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
