# Generated by Django 2.2.12 on 2020-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_is_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
