# Generated by Django 2.2.12 on 2020-06-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200619_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='accounts.Member'),
        ),
    ]
