# Generated by Django 2.2.12 on 2020-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200619_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_private',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
