# Generated by Django 2.2.12 on 2020-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PredefineAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'predefined attribute value',
                'verbose_name_plural': 'predefined attribute values',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('low_stock', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('mark_as_new', models.BooleanField(default=False)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('not_returnable', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('allow_reviews', models.BooleanField(default=False)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_aux', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('low_stock', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('mark_as_new', models.BooleanField(default=False)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('not_returnable', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('allow_reviews', models.BooleanField(default=False)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lenght', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product bundle',
                'verbose_name_plural': 'product bundles',
            },
        ),
    ]
