# Generated by Django 2.2.12 on 2020-07-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('direct_messages', '0002_auto_20200705_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
        ),
    ]
