# Generated by Django 2.2.12 on 2020-07-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('direct_messages', '0003_channel_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
