# Generated by Django 2.2.12 on 2020-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
