# Generated by Django 2.2.12 on 2020-06-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='campaign',
        ),
    ]
