# Generated by Django 2.2.12 on 2020-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_user'),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='allowed_members',
            field=models.ManyToManyField(blank=True, related_name='private_topics', to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='topic',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_topics', to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
