# Generated by Django 2.2.12 on 2020-06-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20200611_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='discussions.Topic'),
            preserve_default=False,
        ),
    ]
