# Generated by Django 2.2.12 on 2020-06-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_user'),
        ('discussions', '0002_auto_20200603_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('is_private', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_members', models.ManyToManyField(blank=True, related_name='private_conversations', to='accounts.Member')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.Member')),
                ('blacklist', models.ManyToManyField(blank=True, related_name='blacklisted_conversations', to='accounts.Member')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
            },
        ),
        migrations.RemoveField(
            model_name='reply',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='allowed_members',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='moderator',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='discussions.Topic'),
        ),
        migrations.AddField(
            model_name='reply',
            name='conversation',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.Conversation'),
            preserve_default=False,
        ),
    ]
