# Generated by Django 2.2.12 on 2020-04-28 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('funds_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('funds_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('funds_available', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('is_open', models.BooleanField(blank=True, default=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('closing_statement', models.TextField(blank=True, null=True)),
                ('volunteers_needed', models.PositiveIntegerField(blank=True, default=0)),
                ('initiator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.Member')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('is_complete', models.BooleanField(blank=True, default=False)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='campaigns.Campaign')),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('is_complete', models.BooleanField(blank=True, default=False)),
                ('goal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='campaigns.Goal')),
            ],
            options={
                'verbose_name': 'objective',
                'verbose_name_plural': 'objectives',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('is_complete', models.BooleanField(blank=True, default=False)),
                ('objective', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='campaigns.Objective')),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked')], max_length=20)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'verbose_name': 'volunteer',
                'verbose_name_plural': 'volunteers',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='campaigns.Campaign')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_led', to='accounts.Member')),
                ('members', models.ManyToManyField(related_name='teams', to='accounts.Member')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('is_complete', models.BooleanField(blank=True, default=False)),
                ('assignees', models.ManyToManyField(related_name='assignments', to='accounts.Member')),
                ('strategy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.Strategy')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='campaigns.Team'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteer_work', through='campaigns.Volunteer', to='accounts.Member'),
        ),
    ]
