# Generated by Django 2.2.12 on 2020-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200502_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='percent_complete',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='objective',
            name='percent_complete',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='percent_complete',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='percent_complete',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
